# Generated by Django 4.0.2 on 2022-02-11 14:36

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Motabari3',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('name', models.CharField(max_length=200)),
                ('age', models.IntegerField()),
                ('wilaya', models.CharField(max_length=200)),
                ('commun', models.CharField(max_length=200)),
                ('phone', models.CharField(max_length=10)),
                ('zomra', models.CharField(choices=[('O+', 'O+'), ('A+', 'A+'), ('AB+', 'AB+'), ('B+', 'B+'), ('O-', 'O-'), ('AB-', 'AB-'), ('A-', 'A-'), ('B-', 'B-')], max_length=200)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
